bird_breeds = [
    "albatross",
    "American coot",
    "American eagle",
    "American egret",
    "American robin",
    "Aptenodytes patagonica",
    "Aramus pictus",
    "Arenaria interpres",
    "bald eagle",
    "bee eater",
    "bittern",
    "black grouse",
    "black stork",
    "black swan",
    "Bonasa umbellus",
    "brambling",
    "bulbul",
    "bustard",
    "Cacatua galerita",
    "Carduelis carduelis",
    "Carpodacus mexicanus",
    "chickadee",
    "Ciconia ciconia",
    "Ciconia nigra",
    "cock",
    "coucal",
    # "crane",
    "Cygnus atratus",
    # "dipper",
    "dowitcher",
    # "drake",
    "dunlin",
    "Egretta albus",
    "Egretta caerulea",
    "Erolia alpina",
    "flamingo",
    "Fringilla montifringilla",
    "Fulica americana",
    "goldfinch",
    "goose",
    "great gray owl",
    "great grey owl",
    "great white heron",
    "Haliaeetus leucocephalus",
    "hen",
    "hornbill",
    "house finch",
    "hummingbird",
    "indigo bird",
    "indigo bunting",
    "indigo finch",
    "jacamar",
    "jay",
    "junco",
    "Kakatoe galerita",
    "king penguin",
    # "kite",
    "limpkin",
    "linnet",
    "little blue heron",
    "lorikeet",
    "macaw",
    "magpie",
    "marsh hen",
    "mollymawk",
    "mud hen",
    "ostrich",
    "oyster catcher",
    "oystercatcher",
    "partridge",
    "partridge",
    "Passerina cyanea",
    "peacock",
    "pelican",
    "prairie chicken",
    "prairie fowl",
    "prairie grouse",
    "ptarmigan",
    "quail",
    "red-backed sandpiper",
    "redshank",
    "robin",
    "ruddy turnstone",
    "ruffed grouse",
    "snowbird",
    "spoonbill",
    "Strix nebulosa",
    "Struthio camelus",
    "sulphur-crested cockatoo",
    "toucan",
    "Tringa totanus",
    "Turdus migratorius",
    "vulture",
    "water hen",
    "water ouzel",
    "white stork",
]
