wild_canid_breeds = [
    "African hunting dog",
    "Canis dingo",
    "Cape hunting dog",
    "Cuon alpinus",
    "dhole",
    "dingo",
    "hyena dog",
    "Lycaon pictus",
    "warragal",
    "warrigal",
]

dog_breeds = [
    "affenpinscher",
    # "Afghan",
    "Afghan hound",
    "Airedale",
    "Airedale terrier",
    "Alaskan malamute",
    "alsatian",
    "American pit bull terrier",
    "American Staffordshire terrier",
    "Australian terrier",
    "basset",
    "basset hound",
    "beagle",
    "Bedlington terrier",
    "Bernese mountain dog",
    "black-and-tan coonhound",
    "Blenheim spaniel",
    "bloodhound",
    "bobtail",
    "Border collie",
    "Border terrier",
    "borzoi",
    "Boston bull",
    "Boston terrier",
    "Bouvier des Flandres",
    "Bouviers des Flandres",
    # "boxer",
    "Brabancon griffon",
    "briard",
    "Brittany spaniel",
    "bull mastiff",
    "cairn",
    "cairn terrier",
    # "Cardigan",
    "Cardigan Welsh corgi",
    "carriage dog",
    "Chesapeake Bay retriever",
    "Chihuahua",
    # "chow",
    "chow chow",
    "chrysanthemum dog",
    "clumber",
    "clumber spaniel",
    "coach dog",
    "cocker",
    "cocker spaniel",
    "collie",
    "curly-coated retriever",
    "dalmatian",
    "Dandie Dinmont",
    "Dandie Dinmont terrier",
    "deerhound",
    "Doberman",
    "Doberman pinscher",
    "elkhound",
    "English cocker spaniel",
    "English foxhound",
    "English setter",
    "English springer",
    "English springer spaniel",
    "Eskimo dog",
    "flat-coated retriever",
    "French bulldog",
    "gazelle hound",
    "German police dog",
    "German shepherd",
    "German shepherd dog",
    "giant schnauzer",
    "golden retriever",
    "Gordon setter",
    "Greater Swiss Mountain dog",
    "groenendael",
    "Hungarian pointer",
    "husky",
    "Ibizan hound",
    "Ibizan Podenco",
    "Irish setter",
    "Irish terrier",
    "Irish water spaniel",
    "Irish wolfhound",
    "Italian greyhound",
    "Japanese spaniel",
    "keeshond",
    "kelpie",
    "Kerry blue terrier",
    "komondor",
    "kuvasz",
    "Labrador retriever",
    "Lakeland terrier",
    "Leonberg",
    "malamute",
    "malemute",
    "malinois",
    "Maltese",
    "Maltese dog",
    "Maltese terrier",
    "miniature pinscher",
    "miniature poodle",
    "miniature schnauzer",
    "monkey dog",
    "monkey pinscher",
    # "Newfoundland",
    "Newfoundland dog",
    "Norfolk terrier",
    "Norwegian elkhound",
    "Norwich terrier",
    "Old English sheepdog",
    "otter hound",
    "otterhound",
    "papillon",
    "Peke",
    "Pekinese",
    "Pekingese",
    "Pembroke",
    "Pembroke Welsh corgi",
    "pit bull terrier",
    "Pomeranian",
    "pug",
    "pug-dog",
    "red setter",
    "Rhodesian ridgeback",
    "Rottweiler",
    "Russian wolfhound",
    "Saluki",
    "Samoyed",
    "Samoyede",
    "schipperke",
    "Scotch terrier",
    "Scottish deerhound",
    "Scottish terrier",
    "Scottie",
    "Sealyham",
    "Sealyham terrier",
    # "Shetland",
    "Shetland sheep dog",
    "Shetland sheepdog",
    "Shih-Tzu",
    "Siberian husky",
    "silky terrier",
    "sleuthhound",
    "soft-coated wheaten terrier",
    "Staffordshire bull terrier",
    "Staffordshire bullterrier",
    "Staffordshire terrier",
    "standard poodle",
    "standard schnauzer",
    "Sussex spaniel",
    "Sydney silky",
    "Tibetan mastiff",
    "Tibetan terrier",
    "toy poodle",
    "toy terrier",
    "vizsla",
    "Walker foxhound",
    "Walker hound",
    "Weimaraner",
    "Welsh springer spaniel",
    "West Highland white terrier",
    "whippet",
    "wire-haired fox terrier",
    "Yorkshire terrier",
]
