snake_breeds = [
    "boa constrictor",
    "Carphophis amoenus",
    # "cerastes",  # ambiguous: genus name, not a specific breed
    "Cerastes cornutus",
    # "Constrictor constrictor",  # ambiguous: outdated taxonomy
    "Crotalus adamanteus",
    "Crotalus cerastes",
    # "diamondback",  # ambiguous: could refer to a terrapin
    "diamondback rattlesnake",
    "garter snake",
    "grass snake",
    "green mamba",
    "green snake",
    "hognose snake",
    "horned asp",
    "horned rattlesnake",
    "horned viper",
    "Hypsiglena torquata",
    "Indian cobra",
    "king snake",
    "kingsnake",
    "Naja naja",
    "night snake",
    "puff adder",
    "Python sebae",
    "ring-necked snake",
    "ring snake",
    "ringneck snake",
    "rock python",
    "rock snake",
    "sand viper",
    "sea snake",
    # "sidewinder",  # ambiguous: also a common word for a missile
    "thunder snake",
    "vine snake",
    "water snake",
    "worm snake",
]
